name: doctor_patient
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^5.1.0
  agora_rtc_engine: ^6.2.2
  cached_network_image: ^3.2.3
  country_pickers: ^2.0.0
  dio: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.2
  intl: ^0.18.1
  intro_views_flutter: ^3.2.0
  permission_handler: ^10.4.3
  photo_view: ^0.14.0
  razorpay_flutter: ^1.3.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  side_header_list_view: ^1.0.0-nullsafety.0
  strings: ^2.0.2
  url_launcher: ^6.1.12
  path_provider: ^2.1.0
  flutter_typeahead: ^4.6.2
#  flutter_chips_input: ^2.0.0
  intro_slider: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.jpg"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/